### PR TITLE
value.length fixes

### PR DESCRIPTION
**Pull request by zinthemoney**

### CODE REVIEW

**Comment by josefdlange** [comment]
@zinthemoney, you should probably clean up the test cases so that this can be pulled in.

**Comment by zinthemoney** [comment]
Maintainer isn't responding, we might start maintaining the fork if they don't respond at all. We might do that anyway actually:)




Good point on fixing the tests :)

**Comment by plandem** [comment]
About EXC_BAD_ACCESS. I suppose that I understand problem, but i can't reproduce it :( If i'm right, it's about something like this: http://www.cocoawithlove.com/2011/06/big-weakness-of-objective-c-weak-typing.html

I tried to fix it, but  as i said - can't reproduce in tests, so i'm sure that this fix actually works like supposed. Guys, can you test? Or i need sample how to reproduce this behaviour.

**Comment by josefdlange** [comment]
I ran into it (and I'm reaching here, I forget the exact circumstance) when I had an empty string as a default. I forget if that default was the default for the form config or for some portion of the validation config. (I don't have the code in front of me!)

I'll try a test case or two out tonight perhaps.

**Comment by plandem** [comment]
so last update helped? no more crashes?

**Comment by josefdlange** [comment]
Update works, but the pod spec hasn't been updated to reflect it.

**Comment by plandem** [comment]
yes, because i wanted to test before release it. And i had not crashes locally :(

**Comment by plandem** [comment]
fixed

**Comment by josefdlange** [comment]
That's right, I remember. Sorry about that. Thanks for taking the changes nonetheless.

**Pull request closed without merging**
